import { type NextPage } from "next";
import Head from "next/head";
import { SearchBar } from "../components/SearchBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-12 pt-72 md:pt-0 md:h-screen flex items-center justify-center">
        <div>
          <h1 className="font-semibold text-slate-800 text-center text-5xl mb-6">
            Welcome to <span className="text-indigo-700">Now Steaming!</span>
          </h1>

          <SearchBar width='full' />
        </div>
      </main>
    </>
  );
};

export default Home;
